package pl.edu.agh.araucaria;/*
 * pl.edu.agh.araucaria.MarkingDialog.java
 *
 * Created on 05 March 2004, 15:25
 */

/**
 * @author growe
 */

import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;
import org.xml.sax.helpers.XMLReaderFactory;
import pl.edu.agh.araucaria.xml.XMLErrorHandler;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.CharArrayReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.DecimalFormat;
import java.util.Vector;

public class MarkingDialog extends javax.swing.JDialog {
    public Argument tutorArg, studentArg;
    JFileChooser xmlChoice;
    File lastDirectory;
    Vector tutorTrav, studentTrav;
    /**
     * Compares the vertexes in the tutor's and student's diagrams.
     * For each vertex in the tutor's diagram, the corresponding vertex in the student's
     * diagram is found (if there is one). The children of the tutor and student vertexes
     * are then compared to see if they are the same.
     */
    int vertexCount, vertexMatch;
    private javax.swing.JButton markButton;
    private javax.swing.JTextArea resultsTextArea;
    private javax.swing.JLabel studentFileLabel;
    private javax.swing.JLabel tutorFileLabel;

    /**
     * Creates new form pl.edu.agh.araucaria.MarkingDialog
     */
    public MarkingDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ExtensionFileFilter xmlFilter = new ExtensionFileFilter();
        xmlFilter.addExtension("aml");
        xmlChoice = new JFileChooser();
        xmlChoice.setFileFilter(xmlFilter);
    }

    /**
     * Constructor for command line marking
     */
    public MarkingDialog() {
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;

        JPanel fileButtonPanel = new JPanel();
        JButton tutorButton = new JButton();
        JButton studentButton = new JButton();
        markButton = new javax.swing.JButton();
        tutorFileLabel = new javax.swing.JLabel();
        studentFileLabel = new javax.swing.JLabel();
        JScrollPane resultsScrollPane = new JScrollPane();
        resultsTextArea = new javax.swing.JTextArea();
        JPanel closePanel = new JPanel();
        JButton closeButton = new JButton();

        setTitle("Mark student's diagram");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog();
            }
        });

        fileButtonPanel.setLayout(new java.awt.GridBagLayout());

        tutorButton.setText("Tutor");
        tutorButton.setToolTipText("Load the tutor's solution");
        tutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorButtonActionPerformed();
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        fileButtonPanel.add(tutorButton, gridBagConstraints);

        studentButton.setText("Student");
        studentButton.setToolTipText("Load the student's solution");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed();
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        fileButtonPanel.add(studentButton, gridBagConstraints);

        markButton.setText("Mark");
        markButton.setToolTipText("Mark student's diagram");
        markButton.setEnabled(false);
        markButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markButtonActionPerformed();
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        fileButtonPanel.add(markButton, gridBagConstraints);

        tutorFileLabel.setText("Tutor file: (not loaded)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        fileButtonPanel.add(tutorFileLabel, gridBagConstraints);

        studentFileLabel.setText("Student file: (not loaded)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        fileButtonPanel.add(studentFileLabel, gridBagConstraints);

        getContentPane().add(fileButtonPanel, java.awt.BorderLayout.NORTH);

        resultsTextArea.setEditable(false);
        resultsTextArea.setToolTipText("Display results of marking");
        resultsScrollPane.setViewportView(resultsTextArea);

        getContentPane().add(resultsScrollPane, java.awt.BorderLayout.CENTER);

        closeButton.setText("Close");
        closeButton.setToolTipText("Close the dialog");
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed();
            }
        });

        closePanel.add(closeButton);

        getContentPane().add(closePanel, java.awt.BorderLayout.SOUTH);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 550) / 2, (screenSize.height - 300) / 2, 550, 300);
    }//GEN-END:initComponents

    private void markButtonActionPerformed() {//GEN-FIRST:event_markButtonActionPerformed
        resultsTextArea.setText(buildPremiseTable());
    }//GEN-LAST:event_markButtonActionPerformed

    public String buildPremiseTable() {
        Tree studentTree = studentArg.getTree();
        Tree tutorTree = tutorArg.getTree();
        TreeVertex root = (TreeVertex) tutorTree.getRoots().elementAt(0);
        tutorTrav = tutorArg.getTree().breadthFirstTraversal(root);
        root = (TreeVertex) studentTree.getRoots().elementAt(0);
        studentTrav = studentArg.getTree().breadthFirstTraversal(root);
        for (int i = 0; i < studentTrav.size(); i++) {
            TreeVertex studentVertex = (TreeVertex) studentTrav.elementAt(i);
            studentVertex.clearTutorParameters();
        }
        // For each tutor vertex, try to find a matching student vertex
        for (int i = 0; i < tutorTrav.size(); i++) {
            TreeVertex tutorVertex = (TreeVertex) tutorTrav.elementAt(i);
            tutorVertex.clearTutorParameters();
            TreeVertex testTutorVertex;
            // If tutorVertex is virtual, we use the properties of its parent.
            // This is necessary since virtual nodes don't have any text associated
            // with them, so we can't compare them directly
            if (tutorVertex.isVirtual()) {
                testTutorVertex = tutorVertex.getParent();
            } else {
                testTutorVertex = tutorVertex;
            }
            int tutorStart = testTutorVertex.getTutorStart();
            int tutorEnd = testTutorVertex.getTutorEnd();
            int tutorOffset = testTutorVertex.getOffset();
            String tutorText = testTutorVertex.getLabel().toString();
            // If start & end markers are both 0, means that no flexible endpoints
            // have been defined for this vertex, so just use exact selected text
            if (tutorStart == 0 && tutorEnd == 0) {
                tutorStart = tutorOffset;
                tutorEnd = tutorStart + tutorText.length();
            }
            // The range of acceptable endpoints in student vertex is between tutorStart and tutorEnd
            for (int s = 0; s < studentTrav.size(); s++) {
                TreeVertex studentVertex = (TreeVertex) studentTrav.elementAt(s);
                TreeVertex testStudentVertex;
                if (studentVertex.isVirtual()) {
                    testStudentVertex = studentVertex.getParent();
                } else {
                    testStudentVertex = studentVertex;
                }
                int studentOffset = testStudentVertex.getOffset();
                String studentText = testStudentVertex.getLabel().toString();
                if (studentOffset >= tutorStart && studentOffset <= tutorOffset &&
                        studentOffset + studentText.length() >= tutorOffset + tutorText.length() &&
                        studentOffset + studentText.length() <= tutorEnd &&
                        studentVertex.isVirtual() == tutorVertex.isVirtual()) {
                    // If the matching vertices are not virtual, map them onto each other
                    if (!studentVertex.isVirtual()) {
                        studentVertex.tutorLink = tutorVertex;
                        tutorVertex.studentLink = studentVertex;
                        // Otherwise if they are virtual, add the student virtual vertex to
                        // the tutor virtual vertex's parent's list of virtual vertices to check.
                        // This allows for the parent having more than one virtual child.
                    } else {
                        tutorVertex.getParent().studentVirtualList.add(studentVertex);
                    }
          /*
          System.out.println("Matched student " + studentOffset + " to " + tutorStart + " - " + tutorOffset +
            " end... " + (studentOffset + studentText.length()) + " to " +
            (tutorOffset + tutorText.length()) + " - " + tutorEnd);*/
                }
            }
        }

        // Display results
        String summary = "";
        int premiseCount = 0, premiseMatch = 0;
        for (int i = 0; i < tutorTrav.size(); i++) {
            TreeVertex tutorVertex = (TreeVertex) tutorTrav.elementAt(i);
            TreeVertex student = tutorVertex.studentLink;
            if (!tutorVertex.isVirtual()) {
                premiseCount++;
            }
            if (student != null) {
                premiseMatch++;
            }
        }
        DecimalFormat formatter = new DecimalFormat("##.##");
        summary += "Premises: " + formatter.format(100 * (float) premiseMatch / premiseCount);

        summary += "; pl.edu.agh.araucaria.Vertex matches: " + formatter.format(100 * (float) vertexMatch / vertexCount);

        return summary;
    }

    private void closeButtonActionPerformed() {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void studentButtonActionPerformed() {//GEN-FIRST:event_studentButtonActionPerformed
        studentArg = new Argument();
        readXML(studentArg, "Student file: ", studentFileLabel);
        if (studentArg != null && tutorArg != null) {
            markButton.setEnabled(true);
        } else {
            markButton.setEnabled(false);
        }
    }//GEN-LAST:event_studentButtonActionPerformed

    private void tutorButtonActionPerformed() {//GEN-FIRST:event_tutorButtonActionPerformed
        tutorArg = new Argument();
        readXML(tutorArg, "Tutor file: ", tutorFileLabel);
        if (studentArg != null && tutorArg != null) {
            markButton.setEnabled(true);
        } else {
            markButton.setEnabled(false);
        }
    }//GEN-LAST:event_tutorButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog() {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void readXML(Argument arg, String labelPrefix, JLabel label) {
        String fileName;
        File chosenFile = null;
        try {
            xmlChoice.setDialogTitle("Open argument");
            // Sets directory to amlDirectory specified in preferences
            xmlChoice.setCurrentDirectory(new File(Araucaria.amlDirectory));
            if (xmlChoice.showOpenDialog(null) !=
                    JFileChooser.APPROVE_OPTION) {
                return;
            }
            lastDirectory = xmlChoice.getCurrentDirectory();
            chosenFile = xmlChoice.getSelectedFile();
            // See if user has typed in the .aml suffix. If not, add it.
            if (!chosenFile.getPath().contains(".aml")) {
                String newPath = chosenFile.getPath() + ".aml";
                chosenFile = new File(newPath);
            }
            if (!chosenFile.exists()) {
                // Add a JOptionPane here
                return;
            }
            fileName = chosenFile.getAbsolutePath();
            label.setText(labelPrefix + fileName);
        } catch (Exception ignored) {
        }
        String result = processFile(arg, chosenFile);
        if (!result.equals("OK")) {
            resultsTextArea.setText(result);
        }
    }

    public String processFile(Argument arg, File chosenFile) {
        String fileName = chosenFile.getAbsolutePath();
        try {
            arg.emptyTree(true);
            // Try using SAX to parse the XML file
            FileInputStream fileStream = new FileInputStream(fileName);
            char inBuffer[] = new char[(int) chosenFile.length()];

            InputStreamReader isReader = new InputStreamReader(fileStream, "UTF-8");
            BufferedReader r = new BufferedReader(isReader);
            int charsRead = r.read(inBuffer, 0, inBuffer.length);
            String text = new String(inBuffer);
            text = text.substring(0, charsRead);
            inBuffer = text.toCharArray();
            CharArrayReader charReader = new CharArrayReader(inBuffer);
            fileStream.close();

            InputSource saxInput = new InputSource(charReader);
            parseXMLwithSAX(saxInput, arg.getTree());
        } catch (IOException e) {
            return "Error reading URI: " + e.getMessage();
        } catch (SAXException e) {
            e.printStackTrace();
            return "Error in parsing " + fileName + ": " + e.getMessage();
        } catch (Exception e) {
            return "Error: " + fileName;
        } catch (Error e) {
            return "Error: " + fileName;
        }
        return "OK";
    }

    /**
     * This version uses a pl.edu.agh.araucaria.TutorContentHandler
     * to do the parsing. This builds the tree & text but ignores all graphics.
     */
    public void parseXMLwithSAX(InputSource source, Tree tree) throws Exception {
        org.xml.sax.ContentHandler contentHandler =
                new TutorContentHandler(tree);
        org.xml.sax.ErrorHandler errorHandler = new XMLErrorHandler();
        XMLReader parser =
                XMLReaderFactory.createXMLReader();
        //"org.apache.xerces.parsers.SAXParser");
        parser.setContentHandler(contentHandler);
        parser.setErrorHandler(errorHandler);
        parser.setFeature("http://xml.org/sax/features/validation", true);
        parser.setFeature("http://xml.org/sax/features/namespaces", false);
        parser.parse(source);
    }
    // End of variables declaration//GEN-END:variables

}
